services:
  - type: worker
    name: rt-telegram-reddit-bot
    env: python
    rootDir: telegram_reddit_bot
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py --mode daemon
    autoDeploy: true


